[package]
name = "ferrum"
version = "0.0.0"
publish = false
build = "build.rs"
edition = "2021"
exclude = ["artifacts.json"]

[lib]
path = "src-native/lib.rs"
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "2.0"

[dependencies]
napi = { version = "2.9", features = ["serde-json", "napi6", "tokio_rt"] }
napi-derive = "2.9"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
id3 = "1.1"
mp3-metadata = "0.3"
mp4ameta = "0.11"
lofty = "0.7"
serde_json = "1.0"
nanoid = "0.4"
alphanumeric-sort = "1.4"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
atomicwrites = "0.3"
trash = "2.0"
base64 = "0.13"
plist = "1.3"
tokio = { version = "1.21", features = ["macros"] }
time = { version = "0.3", features = ["serde", "serde-well-known"] }
url = "2.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
