[package]
name = "ferrum"
version = "0.0.0"
publish = false
build = "build.rs"
edition = "2021"
exclude = ["artifacts.json"]

[lib]
path = "src-native/lib.rs"
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "2.0"

[dependencies]
napi = { version = "2.13", features = ["serde-json", "napi6", "tokio_rt"] }
napi-derive = "2.13"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
id3 = "1.7"
mp3-metadata = "0.3"
mp4ameta = "0.11"
lofty = "0.14"
serde_json = "1.0"
nanoid = "0.4"
alphanumeric-sort = "1.5"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
atomicwrites = "0.4"
trash = "3.0"
plist = { git = "https://github.com/ebarnard/rust-plist", rev = "2e90783310622d78696cd7f797d43b8a22a656de" }
tokio = { version = "1.28", features = ["macros"] }
time = { version = "0.3", features = ["serde", "serde-well-known"] }
url = "2.4"
unicode-normalization = "0.1"
rayon = "1.7.0"

[patch.crates-io]
# For allowing integer version field in Library.json (https://github.com/serde-rs/serde/pull/2056)
serde = { git = "https://github.com/AmaranthineCodices/serde", rev = "47ac87c5e0747e24eb4b4ee513b119b0254ac01f" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
