[package]
name = "ferrum"
version = "0.0.0"
publish = false
build = "build.rs"
edition = "2021"
exclude = ["artifacts.json"]

[lib]
path = "src-native/lib.rs"
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "2.0"

[dependencies]
napi = { version = "2.12", features = ["serde-json", "napi6", "tokio_rt"] }
napi-derive = "2.12"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
id3 = "1.6"
mp3-metadata = "0.3"
mp4ameta = "0.11"
lofty = "0.11"
serde_json = "1.0"
nanoid = "0.4"
alphanumeric-sort = "1.5"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
atomicwrites = "0.4"
trash = "3.0"
plist = { git = "https://github.com/ebarnard/rust-plist", rev = "2e90783310622d78696cd7f797d43b8a22a656de" }
tokio = { version = "1.27", features = ["macros"] }
time = { version = "0.3", features = ["serde", "serde-well-known"] }
url = "2.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
