name: Release
on:
  push:
    tags:
      - 'v*'
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: macos-latest, arg: --mac }
          - { os: ubuntu-latest, arg: --linux }
          - { os: windows-latest, arg: --windows }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install
      - run: npm run napi
      - run: npm run build:web
      - run: npm run electron-builder -- ${{ matrix.arg }} --publish always -c.releaseInfo.releaseName=""
        env:
          GH_TOKEN: ${{ secrets.github_token }}
